name: ShadowMasterProject
options:
  bundleIdPrefix: com.shadow.v11
targets:
  ShadowMaster:
    type: library.dynamic
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: "ShadowMaster.m"
    frameworks:
      - framework: Foundation.framework
      - framework: UIKit.framework
      - framework: CoreML.framework
      - framework: Security.framework
    settings:
      ENABLE_BITCODE: NO
      OTHER_LDFLAGS: $(inherited) -undefined dynamic_lookup -all_load
      GCC_DYNAMIC_NO_PIC: NO
      WARNING_CFLAGS: "-Wno-everything"
      PRODUCT_NAME: ShadowMaster
