name: ShadowMasterProject
targets:
  ShadowMaster:
    type: library.dynamic
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - "SHADOW MASTER v11.m"
      - "ShadowUI.m"
    settings:
      PRODUCT_NAME: ShadowMaster
      CLANG_ENABLE_OBJC_ARC: YES
